### ISSUE TITLE
Can't seem to setup vnc server

### ISSUE THREAD

**Issue by InfamousKnight** [ahmed-alnassif/AndroSH#4]
After following this guide https://ipv6.rs/tutorial/Alpine_Linux_Latest/Tiger_VNC/

It ends with "could not find desktop session. I did install cinnamon-desktop but I don't know what i did wrong..

**Comment by ahmed-alnassif** [comment]
Can u send screenshots?
And your commands?

**Comment by InfamousKnight** [comment]
androsh launch dev

Now inside alpine environment.
apk update
apk upgrade
apk add tigervnc

![Image](https://github.com/user-attachments/assets/3ef26518-5a5c-45e6-8294-5fa5d08f8051)

**Comment by ahmed-alnassif** [comment]
> androsh launch dev
> 
> Now inside alpine environment.
> apk update
> apk upgrade
> apk add tigervnc
> 
> ![Image](https://github.com/user-attachments/assets/3ef26518-5a5c-45e6-8294-5fa5d08f8051)

Use these commands:
```
#!/bin/sh

# Update and install only what's needed
apk update
apk add x11vnc xvfb

# Create and start VNC
cat > /usr/local/bin/start-vnc.sh << 'EOF'
#!/bin/sh
echo "Starting VNC server..."
export DISPLAY=:99
Xvfb :99 -screen 0 1024x768x24 -ac &
sleep 2
#[add your desktop startup command here] &
x11vnc -display :99 -forever -shared -nopw -listen 0.0.0.0 -rfbport 5900
EOF

chmod +x /usr/local/bin/start-vnc.sh

start-vnc.sh
```

Try this simple setup, without complex and a working vnc server.

Replace #[add your desktop startup command here] with your desktop environment command.

A commad will created and you can use it when you want to start the server.
The command:
```bash
start-vnc.sh
```

**Comment by ahmed-alnassif** [comment]
> What's the desktop startup command for cinnamo?
The command is:
```bash
cinnamon-session
```
If u want me to edit the script tell me.

**Comment by InfamousKnight** [comment]
Yeah sure. It still doesn't work I guess?

And what about rvnc login for port and address?


localhost:~# #!/bin/sh
localhost:~#
localhost:~# # Update and install only what's needed
localhost:~# apk update
fetch https://dl-cdn.alpinelinux.org/alpine/v3.22/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.22/community/aarch64/APKINDEX.tar.gz
v3.22.2-142-g5fc470561e9 [https://dl-cdn.alpinelinux.org/alpine/v3.22/main]
v3.22.2-153-ga317629c97a [https://dl-cdn.alpinelinux.org/alpine/v3.22/community]
OK: 26161 distinct packages available
localhost:~# apk add x11vnc xvfb
(1/66) Installing libxau (1.0.12-r0)
(2/66) Installing libmd (1.1.0-r0)
(3/66) Installing libbsd (0.12.2-r0)
(4/66) Installing libxdmcp (1.1.5-r1)
(5/66) Installing libxcb (1.17.0-r0)
(6/66) Installing libx11 (1.8.11-r0)
(7/66) Installing libxdamage (1.1.6-r5)
(8/66) Installing libxext (1.3.6-r2)
(9/66) Installing libxfixes (6.0.1-r4)
(10/66) Installing libxi (1.8.2-r0)
(11/66) Installing libxinerama (1.1.5-r4)
(12/66) Installing libxrender (0.9.12-r0)
(13/66) Installing libxrandr (1.5.4-r1)
(14/66) Installing libxtst (1.2.5-r0)
(15/66) Installing dbus-libs (1.16.2-r1)
(16/66) Installing libintl (0.24.1-r0)
(17/66) Installing avahi-libs (0.8-r21)
(18/66) Installing libgpg-error (1.55-r0)
(19/66) Installing libgcrypt (1.10.3-r1)
(20/66) Installing libjpeg-turbo (3.1.0-r0)
(21/66) Installing lzo (2.10-r5)
(22/66) Installing libpng (1.6.47-r0)
(23/66) Installing libvncserver (0.9.15-r0)
(24/66) Installing x11vnc (0.9.17-r0)
(25/66) Installing encodings (1.0.7-r1)
(26/66) Installing font-alias (1.0.5-r0)
(27/66) Installing libfontenc (1.1.8-r0)
(28/66) Installing brotli-libs (1.1.0-r2)
(29/66) Installing libbz2 (1.0.8-r6)
(30/66) Installing freetype (2.13.3-r0)
(31/66) Installing mkfontscale (1.2.3-r1)
(32/66) Installing libexpat (2.7.3-r0)
(33/66) Installing fontconfig (2.15.0-r3)
(34/66) Installing pkgconf (2.4.3-r0)
(35/66) Installing util-macros (1.20.1-r0)
(36/66) Installing font-cursor-misc (1.0.4-r1)
(37/66) Installing font-misc-misc (1.1.3-r1)
(38/66) Installing libffi (3.4.8-r0)
(39/66) Installing libgcc (14.2.0-r6)
(40/66) Installing libstdc++ (14.2.0-r6)
(41/66) Installing xz-libs (5.8.1-r0)
(42/66) Installing libxml2 (2.13.9-r0)
(43/66) Installing zstd-libs (1.5.7-r0)
(44/66) Installing llvm20-libs (20.1.8-r0)
(45/66) Installing spirv-tools (1.4.313.0-r0)
(46/66) Installing hwdata-pci (0.395-r0)
(47/66) Installing libpciaccess (0.18.1-r0)
(48/66) Installing libdrm (2.4.124-r0)
(49/66) Installing libelf (0.193-r0)
(50/66) Installing wayland-libs-server (1.23.1-r3)
(51/66) Installing libxshmfence (1.3.3-r0)
(52/66) Installing mesa (25.1.9-r0)
(53/66) Installing mesa-gbm (25.1.9-r0)
(54/66) Installing wayland-libs-client (1.23.1-r3)
(55/66) Installing mesa-egl (25.1.9-r0)
(56/66) Installing libxkbfile (1.1.3-r0)
(57/66) Installing xkbcomp (1.4.7-r0)
(58/66) Installing xkeyboard-config (2.43-r0)
(59/66) Installing xorg-server-common (21.1.19-r0)
(60/66) Installing libxxf86vm (1.1.6-r0)
(61/66) Installing mesa-gl (25.1.9-r0)
(62/66) Installing libxfont2 (2.0.7-r0)
(63/66) Installing gmp (6.3.0-r3)
(64/66) Installing nettle (3.10.1-r0)
(65/66) Installing pixman (0.46.4-r0)
(66/66) Installing xvfb (21.1.19-r0)
Executing busybox-1.37.0-r19.trigger
Executing mkfontscale-1.2.3-r1.trigger
Executing fontconfig-2.15.0-r3.trigger
OK: 291 MiB in 82 packages
localhost:~#
localhost:~# # Create and start VNC
localhost:~# cat > /usr/local/bin/start-vnc.sh << 'EOF
'
> #!/bin/sh
> echo "Starting VNC server..."
> export DISPLAY=:99
> Xvfb :99 -screen 0 1024x768x24 -ac &
> sleep 2
> cinnamon-session &
> x11vnc -display :99 -forever -shared -nopw -listen 0
.0.0.0 -rfbport 5900
> EOF
localhost:~#
localhost:~# chmod +x /usr/local/bin/start-vnc.sh
localhost:~#
localhost:~# start-vnc.sh
Starting VNC server...
_XSERVTransSocketCreateListener: failed to bind listener
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: failed to create listener for unix
/usr/local/bin/start-vnc.sh: line 6: cinnamon-session: not found
07/11/2025 22:41:20 passing arg to libvncserver: -listen
07/11/2025 22:41:20 passing arg to libvncserver: 0.0.0.0
07/11/2025 22:41:20 passing arg to libvncserver: -rfbport
07/11/2025 22:41:20 passing arg to libvncserver: 5900
07/11/2025 22:41:20 x11vnc version: 0.9.17 lastmod: 2025-04-11  pid: 18315
07/11/2025 22:41:20 Using X display :99
07/11/2025 22:41:20 rootwin: 0x42 reswin: 0x200001 dpy: 0x1077b030
07/11/2025 22:41:20
07/11/2025 22:41:20 ------------------ USEFUL INFORMATION ------------------
07/11/2025 22:41:20 X DAMAGE available on display, using it for polling hints.
07/11/2025 22:41:20   To disable this behavior use: '-noxdamage'
07/11/2025 22:41:20
07/11/2025 22:41:20   Most compositing window managers like 'compiz' or 'beryl'
07/11/2025 22:41:20   cause X DAMAGE to fail, and so you may not see any screen
07/11/2025 22:41:20   updates via VNC.  Either disable 'compiz' (recommended) or
07/11/2025 22:41:20   supply the x11vnc '-noxdamage' command line option.
07/11/2025 22:41:20
07/11/2025 22:41:20 Wireframing: -wireframe mode is in effect for window moves.
07/11/2025 22:41:20   If this yields undesired behavior (poor response, painting
07/11/2025 22:41:20   errors, etc) it may be disabled:
07/11/2025 22:41:20    - use '-nowf' to disable wireframing completely.
07/11/2025 22:41:20    - use '-nowcr' to disable the Copy Rectangle after the
07/11/2025 22:41:20      moved window is released in the new position.
07/11/2025 22:41:20   Also see the -help entry for tuning parameters.
07/11/2025 22:41:20   You can press 3 Alt_L's (Left "Alt" key) in a row to
07/11/2025 22:41:20   repaint the screen, also see the -fixscreen option for
07/11/2025 22:41:20   periodic repaints.
07/11/2025 22:41:20
07/11/2025 22:41:20 XFIXES available on display, resetting cursor mode
07/11/2025 22:41:20   to: '-cursor most'.
07/11/2025 22:41:20   to disable this behavior use: '-cursor arrow'
07/11/2025 22:41:20   or '-noxfixes'.
07/11/2025 22:41:20 using XFIXES for cursor drawing.
07/11/2025 22:41:20 GrabServer control via XTEST.
07/11/2025 22:41:20
07/11/2025 22:41:20 Scroll Detection: -scrollcopyrect mode is in effect to
07/11/2025 22:41:20   use RECORD extension to try to detect scrolling windows
07/11/2025 22:41:20   (induced by either user keystroke or mouse input).
07/11/2025 22:41:20   If this yields undesired behavior (poor response, painting
07/11/2025 22:41:20   errors, etc) it may be disabled via: '-noscr'
07/11/2025 22:41:20   Also see the -help entry for tuning parameters.
07/11/2025 22:41:20   You can press 3 Alt_L's (Left "Alt" key) in a row to
07/11/2025 22:41:20   repaint the screen, also see the -fixscreen option for
07/11/2025 22:41:20   periodic repaints.
07/11/2025 22:41:20
07/11/2025 22:41:20 XKEYBOARD: number of keysyms per keycode 7 is greater
07/11/2025 22:41:20   than 4 and 51 keysyms are mapped above 4.
07/11/2025 22:41:20   Automatically switching to -xkb mode.
07/11/2025 22:41:20   If this makes the key mapping worse you can
07/11/2025 22:41:20   disable it with the "-noxkb" option.
07/11/2025 22:41:20   Also, remember "-remap DEAD" for accenting characters.
07/11/2025 22:41:20
07/11/2025 22:41:20 X FBPM extension not supported.
Xlib:  extension "DPMS" missing on display ":99".
07/11/2025 22:41:20 X display is not capable of DPMS.
07/11/2025 22:41:20 --------------------------------------------------------
07/11/2025 22:41:20
07/11/2025 22:41:20 Default visual ID: 0x21
07/11/2025 22:41:20 Read initial data from X display into framebuffer.
07/11/2025 22:41:20 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/4096
07/11/2025 22:41:20
07/11/2025 22:41:20 X display :99 is 32bpp depth=24 true color
07/11/2025 22:41:20
07/11/2025 22:41:20 Listening for VNC connections on TCP port 5900
07/11/2025 22:41:20 Listening for VNC connections on TCP6 port 5900
07/11/2025 22:41:20 listen6: bind: Address in use
07/11/2025 22:41:20 Not listening on IPv6 interface.
07/11/2025 22:41:20
07/11/2025 22:41:20 Xinerama is present and active (e.g. multi-head).
07/11/2025 22:41:20 Xinerama: number of sub-screens: 1
07/11/2025 22:41:20 Xinerama: no blackouts needed (only one sub-screen)
07/11/2025 22:41:20
proot-shm-helper: bind: Permission denied
07/11/2025 22:41:20 shmget(scanline) failed.
07/11/2025 22:41:20 shmget: No space left on device
localhost:~#

**Comment by InfamousKnight** [comment]
![Image](https://github.com/user-attachments/assets/5c4b0c18-34d3-472d-b88f-611b7f44116c)

Plenty of space

**Comment by ahmed-alnassif** [comment]
@InfamousKnight

**Comment by ahmed-alnassif** [comment]
@InfamousKnight Is the vnc working?

**Comment by InfamousKnight** [comment]
And it says vncserver not found. But it also says its started.

**Comment by InfamousKnight** [comment]
localhost:~# which vncserver
/usr/bin/vncserver
localhost:~# vncserver :1
~/.vnc is deprecated, please consult 'man vncsession' for paths to migrate
to. at /usr/bin/vncserver line 43.
Could not find a desktop session to run
localhost:~#

**Comment by ahmed-alnassif** [comment]
> start-vnc.sh
> ~/.vnc is deprecated, please consult 'man vncsession' for paths to migrate to. at /usr/bin/vncserver line 43.
> 
> usage: vncserver <display>
> 
> VNC server started on display :1
> Connect using: localhost:5901
> To stop: vncserver -kill :1
> localhost:~#

Enter:
```
rm -rf ~/.vnc
```

**Comment by InfamousKnight** [comment]
localhost:~# which cinnamon-session
localhost:~# apk update
v3.22.2-142-g5fc470561e9 [https://dl-cdn.alpinelinux.org/alpine/v3.22/main]
v3.22.2-153-ga317629c97a [
https://dl-cdn.alpinelinux.org/alpine/v3.22/community]
OK: 26161 distinct packages available
localhost:~# apk add tigervnc cinnamon-desktop
OK: 370 MiB in 138 packages
localhost:~#
localhost:~# mkdir -p ~/.vnc

**Comment by ahmed-alnassif** [comment]
> localhost:~# which cinnamon-session
> localhost:~# apk update
> v3.22.2-142-g5fc470561e9 [https://dl-cdn.alpinelinux.org/alpine/v3.22/main]
> v3.22.2-153-ga317629c97a [
> https://dl-cdn.alpinelinux.org/alpine/v3.22/community]
> OK: 26161 distinct packages available
> localhost:~# apk add tigervnc cinnamon-desktop
> OK: 370 MiB in 138 packages
> localhost:~#
> localhost:~# mkdir -p ~/.vnc


You haven't installed cinnamon from the first place, the commands should fix that.

**Comment by InfamousKnight** [comment]
localhost:~# apk add cinnamon
ERROR: unable to select packages:
  cinnamon (no such package):
    required by: world[cinnamon]
localhost:~#

**Comment by InfamousKnight** [comment]
localhost:~# start-vnc.sh
~/.vnc is deprecated, please consult 'man vncsession' for paths to migrate to. at /usr/bin/vncserver line 43.

usage: vncserver <display>

VNC server started on display :1
Connect using: localhost:5901
To stop: vncserver -kill :1

I guess no because I still can't connect even though I followed the steps.

And BTW, because of vncpasswd, you just can't copy and paste the entire script the password field would enter the next commands. So I just copied little bits

**Comment by ahmed-alnassif** [comment]
> localhost:~# start-vnc.sh ~/.vnc is deprecated, please consult 'man vncsession' for paths to migrate to. at /usr/bin/vncserver line 43.
> 
> usage: vncserver
> 
> VNC server started on display :1 Connect using: localhost:5901 To stop: vncserver -kill :1
> 
> I guess no because I still can't connect even though I followed the steps.
> 
> And BTW, because of vncpasswd, you just can't copy and paste the entire script the password field would enter the next commands. So I just copied little bits


Nice, the server is working.
Now exit and relaunch.
Then enter: start-vnc.ssh

**Comment by ahmed-alnassif** [comment]
> localhost:~# start-vnc.sh ~/.vnc is deprecated, please consult 'man vncsession' for paths to migrate to. at /usr/bin/vncserver line 43.
> 
> usage: vncserver
> 
> VNC server started on display :1 Connect using: localhost:5901 To stop: vncserver -kill :1
> 
> I guess no because I still can't connect even though I followed the steps.
> 
> And BTW, because of vncpasswd, you just can't copy and paste the entire script the password field would enter the next commands. So I just copied little bits


You can save it to a script and make things easier, and If you face any issues in the future you can use that script to troubleshooting them.

**Comment by ahmed-alnassif** [comment]
Copy:
```bash
#!/usr/bin/bash

apk update
apk add tigervnc cinnamon-desktop

mkdir -p ~/.vnc
echo Enter new password
vncpasswd

cat > ~/.vnc/xstartup << 'EOF'
#!/bin/sh
export DISPLAY=:1
export XDG_RUNTIME_DIR=/tmp/runtime-$(whoami)
export XDG_DATA_DIRS=/usr/share
export XDG_CONFIG_DIRS=/etc/xdg

exec cinnamon-session
EOF
chmod +x ~/.vnc/xstartup

cat > /usr/local/bin/start-vnc.sh << 'EOF'
#!/bin/sh

export DISPLAY=:1
export XDG_RUNTIME_DIR=/tmp/runtime-$(whoami)

vncserver -kill :1 2>/dev/null || true

rm -f /tmp/.X1-lock /tmp/.X11-unix/X1

vncserver :1 \
  -geometry 1024x768 \
  -depth 24 \
  -localhost no \
  -alwaysshared \
  -nevershared \
  -securitytypes none \
  -xstartup ~/.vnc/xstartup

echo "VNC server started on display :1"
echo "Connect using: localhost:5901"
echo "To stop: vncserver -kill :1"
EOF

chmod +x /usr/local/bin/start-vnc.sh
```

Enter:
```bash
nano setup-vnc.sh
```

And paste it, then, ctrl+s, ctrl+x.
You can use any editor, this is just an example.

**Comment by ahmed-alnassif** [comment]
@InfamousKnight what's the output of start-vnc.sh?

**Comment by InfamousKnight** [comment]
I just did that now

**Comment by InfamousKnight** [comment]
localhost:~# start-vnc.sh

usage: vncserver <display>

VNC server started on display :1
Connect using: localhost:5901
To stop: vncserver -kill :1
localhost:~#

**Comment by InfamousKnight** [comment]
I don't know what's going on.

I can tell you this much: im using the termux from the playstore since the one github doesn't work on android 16.

And im using the shiuku from github. Maybe that's to blame?

**Comment by ahmed-alnassif** [comment]
The solution that will close this issue is:
Exit and relaunch
Then do that step again
After that use:
```bash
#!/usr/bin/bash

apk update
apk add tigervnc cinnamon-desktop

mkdir -p ~/.vnc
echo Enter new password
vncpasswd

cat > ~/.vnc/xstartup << 'EOF'
#!/bin/sh
export DISPLAY=:1
export XDG_RUNTIME_DIR=/tmp/runtime-$(whoami)
export XDG_DATA_DIRS=/usr/share
export XDG_CONFIG_DIRS=/etc/xdg

exec cinnamon-session
EOF
chmod +x ~/.vnc/xstartup

cat > /usr/local/bin/start-vnc.sh << 'EOF'
#!/bin/sh

export DISPLAY=:1
export XDG_RUNTIME_DIR=/tmp/runtime-$(whoami)

vncserver -kill :1 2>/dev/null || true

rm -f /tmp/.X1-lock /tmp/.X11-unix/X1

vncserver :1 \
  -geometry 1024x768 \
  -depth 24 \
  -localhost no \
  -alwaysshared \
  -nevershared \
  -securitytypes none \
  -xstartup ~/.vnc/xstartup

echo "VNC server started on display :1"
echo "Connect using: localhost:5901"
echo "To stop: vncserver -kill :1"
EOF

chmod +x /usr/local/bin/start-vnc.sh
```
Then enter:
```bash
start-vnc.ssh
```
Go to your client, no issues in the server side.
Issue closed.
